--============================================================
-- AGRICONNECT DATABASE SCHEMA (POSTGRESQL)
--============================================================
-- ============================================================
-- DROP TABLES (Optional)
-- ============================================================
DROP TABLE IF EXISTS crops CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS crop_category CASCADE;
DROP TYPE IF EXISTS crop_season CASCADE;
-- ============================================================
-- ENUM TYPES
-- ============================================================
CREATE TYPE user_role AS ENUM ('farmer','employee','admin');
CREATE TYPE crop_category AS ENUM ('cereal','pulse','oilseed','vegetable','fruit', 'other');
CREATE TYPE crop_season AS ENUM ('kharif','rabi','zaid','all');
-- ============================================================
-- FUNCTION FOR updated_at
-- ============================================================
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$
LANGUAGE plpgsql;
-- ============================================================
-- USERS TABLE
-- ============================================================
CREATE TABLE users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(15) UNIQUE NOT NULL,
    email VARCHAR(100),
    password_hash VARCHAR(255) NOT NULL,
    role user_role NOT NULL DEFAULT 'farmer',
    aadhar_number VARCHAR(12),
    village VARCHAR(100),
    district VARCHAR(100),
    state VARCHAR(100) DEFAULT 'Andhra Pradesh',
    pincode VARCHAR(6),
    bank_account VARCHAR(20),
    ifsc_code VARCHAR(11),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);
-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_users_role
ON users(role);
CREATE INDEX idx_users_phone
ON users(phone);
CREATE INDEX idx_users_district
ON users(district);
-- ============================================================
-- UPDATE TRIGGER
-- ============================================================
CREATE TRIGGER trg_users_timestamp
BEFORE UPDATE
ON users
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
-- ============================================================
-- CROPS TABLE
-- ============================================================
CREATE TABLE crops
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    name_telugu VARCHAR(100),
    category crop_category DEFAULT 'cereal',
    govt_price NUMERIC(10,2) NOT NULL,
    unit VARCHAR(20) DEFAULT 'quintal',
    season crop_season DEFAULT 'all',
    is_active BOOLEAN DEFAULT TRUE,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER,
    CONSTRAINT fk_crop_user
        FOREIGN KEY(updated_by)
        REFERENCES users(id)
        ON DELETE SET NULL
);
COMMENT ON COLUMN crops.govt_price
IS 'Government MSP Price Per Quintal';
-- ============================================================
-- CROPS INDEXES
-- ============================================================
CREATE INDEX idx_crop_name
ON crops(name);
CREATE INDEX idx_crop_category
ON crops(category);
CREATE INDEX idx_crop_season
ON crops(season);
CREATE INDEX idx_crop_active
ON crops(is_active);
-- ============================================================
-- SAMPLE USERS
-- Password = Admin@123
-- ============================================================
INSERT INTO users
(name, phone, email, password_hash, role, district, village)
VALUES
(
'System Administrator',
'9000000001',
'admin@agriconnect.gov.in',
'$2b$10$rQZ8kHWnvhSGjOJ1BKYvIeXEXJPQIhVN4VqEYJBdKMHpGkWZe5pAm',
'admin',
'Nellore',
'Secretariat'
),
(
'Ramaiah Sachivalayam',
'9000000002',
'employee1@agriconnect.gov.in',
'$2b$10$rQZ8kHWnvhSGjOJ1BKYvIeXEXJPQIhVN4VqEYJBdKMHpGkWZe5pAm',
'employee',
'Nellore',
'Kovur'
),
(
'Suresh Kumar',
'9000000003',
'farmer1@agriconnect.gov.in',
'$2b$10$rQZ8kHWnvhSGjOJ1BKYvIeXEXJPQIhVN4VqEYJBdKMHpGkWZe5pAm',
'farmer',
'Nellore',
'Allur'
),
(
'Lakshmi Devi',
'9000000004',
'farmer2@agriconnect.gov.in',
'$2b$10$rQZ8kHWnvhSGjOJ1BKYvIeXEXJPQIhVN4VqEYJBdKMHpGkWZe5pAm',
'farmer',
'Nellore',
'Kavali'
),
(
'Venkata Rao',
'9000000005',
'farmer3@agriconnect.gov.in',
'$2b$10$rQZ8kHWnvhSGjOJ1BKYvIeXEXJPQIhVN4VqEYJBdKMHpGkWZe5pAm',
'farmer',
'Nellore',
'Gudur'
);
-- ============================================================
-- SAMPLE CROPS
-- ============================================================
INSERT INTO crops
(name, name_telugu, category, govt_price, season, updated_by)
VALUES
('Paddy (Common)','వరి (సాధారణ)','cereal',2183.00,'kharif',1),

('Paddy (Grade A)','వరి (గ్రేడ్ A)','cereal',2203.00,'kharif',1),

('Wheat','గోధుమ','cereal',2275.00,'rabi',1),

('Maize','మొక్కజొన్న','cereal',2090.00,'kharif',1),

('Groundnut','వేరుశనగ','oilseed',6783.00,'kharif',1),

('Sunflower','పొద్దుతిరుగుడు','oilseed',6760.00,'kharif',1),

('Red Gram (Tur)','కంది పప్పు','pulse',7000.00,'kharif',1),

('Black Gram','మినప పప్పు','pulse',8558.00,'kharif',1),

('Green Gram','పెసర పప్పు','pulse',8682.00,'kharif',1),

('Cotton (Medium)','పత్తి (మీడియం)','other',7121.00,'kharif',1),

('Cotton (Long)','పత్తి (లాంగ్)','other',7521.00,'kharif',1),

('Soybean','సోయాబీన్','oilseed',4600.00,'kharif',1);
-- ============================================================
-- ENUM TYPES
-- ============================================================
CREATE TYPE sell_status AS ENUM
('pending','verified','rejected','approved','scheduled','completed','payment_done');
CREATE TYPE payment_status AS ENUM
('pending','processing','done');
CREATE TYPE service_type AS ENUM
('subsidy','complaint','crop_damage','loan','scheme','other');
CREATE TYPE service_status AS ENUM
('pending','in_progress','escalated','resolved','rejected');
CREATE TYPE priority_level AS ENUM
('low','medium','high','urgent');
-- ============================================================
-- SELL REQUESTS TABLE
-- ============================================================
CREATE TABLE sell_requests
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id INTEGER NOT NULL,
    crop_id INTEGER NOT NULL,
    quantity NUMERIC(10,2) NOT NULL,
    govt_price NUMERIC(10,2),
    expected_amount NUMERIC(12,2),
    image_url VARCHAR(500),
    geo_lat NUMERIC(10,8),
    geo_lng NUMERIC(11,8),
    village VARCHAR(100),
    harvest_date DATE,
    notes TEXT,
    status sell_status DEFAULT 'pending',
    verified_by INTEGER,
    verified_at TIMESTAMP,
    rejection_reason TEXT,
    approved_by INTEGER,
    approved_at TIMESTAMP,
    procurement_date DATE,
    payment_status payment_status DEFAULT 'pending',
    payment_amount NUMERIC(12,2),
    transaction_ref VARCHAR(100),
    payment_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_sell_farmer
        FOREIGN KEY(farmer_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_sell_crop
        FOREIGN KEY(crop_id)
        REFERENCES crops(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_verified_by
        FOREIGN KEY(verified_by)
        REFERENCES users(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_approved_by
        FOREIGN KEY(approved_by)
        REFERENCES users(id)
        ON DELETE SET NULL
);
-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_sell_farmer
ON sell_requests(farmer_id);
CREATE INDEX idx_sell_status
ON sell_requests(status);
CREATE INDEX idx_sell_crop
ON sell_requests(crop_id);
CREATE INDEX idx_sell_created
ON sell_requests(created_at);
-- ============================================================
-- UPDATE TRIGGER
-- ============================================================
CREATE TRIGGER trg_sell_requests_timestamp
BEFORE UPDATE
ON sell_requests
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
-- ============================================================
-- SERVICE REQUESTS
-- ============================================================
CREATE TABLE service_requests
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id INTEGER NOT NULL,
    type service_type NOT NULL,
    subject VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    media_url VARCHAR(500),
    status service_status DEFAULT 'pending',
    priority priority_level DEFAULT 'medium',
    handled_by INTEGER,
    assigned_at TIMESTAMP,
    escalated_to INTEGER,
    escalated_at TIMESTAMP,
    escalation_reason TEXT,
    resolved_at TIMESTAMP,
    resolution_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_service_farmer
        FOREIGN KEY(farmer_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_handled_by
        FOREIGN KEY(handled_by)
        REFERENCES users(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_escalated_to
        FOREIGN KEY(escalated_to)
        REFERENCES users(id)
        ON DELETE SET NULL
);
-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_service_farmer
ON service_requests(farmer_id);
CREATE INDEX idx_service_status
ON service_requests(status);
CREATE INDEX idx_service_type
ON service_requests(type);
CREATE INDEX idx_service_priority
ON service_requests(priority);
-- ============================================================
-- UPDATE TRIGGER
-- ============================================================
CREATE TRIGGER trg_service_requests_timestamp
BEFORE UPDATE
ON service_requests
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
-- ============================================================
-- PROCUREMENT TABLE
-- ============================================================
CREATE TABLE procurement
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER UNIQUE NOT NULL,
    schedule_date DATE NOT NULL,
    schedule_time TIME,
    location VARCHAR(200),
    officer_name VARCHAR(100),
    vehicle_number VARCHAR(20),
    actual_quantity NUMERIC(10,2),
    payment_status payment_status DEFAULT 'pending',
    payment_amount NUMERIC(12,2),
    transaction_ref VARCHAR(100),
    bank_ref VARCHAR(100),
    payment_date TIMESTAMP,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_procurement_request
        FOREIGN KEY(request_id)
        REFERENCES sell_requests(id)
        ON DELETE CASCADE
);
-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_procurement_date
ON procurement(schedule_date);
CREATE INDEX idx_procurement_payment
ON procurement(payment_status);
-- ============================================================
-- UPDATE TRIGGER
-- ============================================================
CREATE TRIGGER trg_procurement_timestamp
BEFORE UPDATE
ON procurement
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
-- ============================================================
-- SAMPLE SELL REQUESTS
-- ============================================================
INSERT INTO sell_requests
(farmer_id,crop_id,quantity,village,status,notes)
VALUES
(3,1,25.50,'Allur','pending','Good quality paddy harvested last week'),
(4,5,15.00,'Kavali','verified','Fresh groundnut harvest'),
(5,7,10.00,'Gudur','approved','Organic red gram'),
(3,10,20.00,'Allur','completed','Medium variety cotton');
-- ============================================================
-- SAMPLE SERVICE REQUESTS
-- ============================================================
INSERT INTO service_requests
(farmer_id,type,subject,description,status,priority)
VALUES
(3,'subsidy','PM-KISAN Payment Delay','I have not received the PM-KISAN payment for the last quarter.','pending','high'),
(4,'complaint','Crop Damage Due to Pests','Groundnut crop damaged by pests.','in_progress','urgent'),
(5,'crop_damage','Flood Damage','Flood damaged my Red Gram crop.','escalated','high'),
(3,'loan','Agricultural Loan','I want to apply for a crop loan.','resolved','medium');
-- ============================================================
-- ENUM TYPES
-- ============================================================
CREATE TYPE entity_type AS ENUM
('sell_request','service_request');
CREATE TYPE notification_type AS ENUM
('info','success','warning','error');
CREATE TYPE target_role AS ENUM
( 'all','farmer','employee','admin');
-- ============================================================
-- REMARKS TABLE
-- ============================================================
CREATE TABLE remarks
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type entity_type NOT NULL,
    entity_id INTEGER NOT NULL,
    message TEXT NOT NULL,
    created_by INTEGER NOT NULL,
    is_internal BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_remarks_user
        FOREIGN KEY(created_by)
        REFERENCES users(id)
        ON DELETE CASCADE
);
-- ============================================================
-- REMARKS INDEXES
-- ============================================================
CREATE INDEX idx_remarks_entity
ON remarks(entity_type, entity_id);
CREATE INDEX idx_remarks_created_by
ON remarks(created_by);
-- ============================================================
-- NOTIFICATIONS TABLE
-- ============================================================
CREATE TABLE notifications
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    type notification_type DEFAULT 'info',
    is_read BOOLEAN DEFAULT FALSE,
    link VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user
        FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);
-- ============================================================
-- NOTIFICATION INDEXES
-- ============================================================
CREATE INDEX idx_notifications_user
ON notifications(user_id);
CREATE INDEX idx_notifications_read
ON notifications(is_read);
-- ============================================================
-- ANNOUNCEMENTS TABLE
-- ============================================================
CREATE TABLE announcements
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    target_role target_role DEFAULT 'all',
    is_active BOOLEAN DEFAULT TRUE,
    created_by INTEGER NOT NULL,
    expires_at DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_announcements_user
        FOREIGN KEY(created_by)
        REFERENCES users(id)
        ON DELETE CASCADE
);
-- ============================================================
-- ANNOUNCEMENTS INDEXES
-- ============================================================
CREATE INDEX idx_announcements_role
ON announcements(target_role);
CREATE INDEX idx_announcements_active
ON announcements(is_active);
-- ============================================================
-- SAMPLE REMARKS
-- ============================================================
INSERT INTO remarks
(entity_type, entity_id, message, created_by, is_internal)
VALUES
('sell_request',1,'Sell request received successfully.',2,FALSE),
('sell_request',2,'Crop quality verified by procurement officer.',2,TRUE),
('service_request',1,'Farmer contacted through phone.',2,FALSE),
('service_request',3,'District agriculture officer informed.',1,TRUE);
-- ============================================================
-- SAMPLE NOTIFICATIONS
-- ============================================================
INSERT INTO notifications(user_id, title, message, type)VALUES
(3,'Sell Request Submitted','Your crop sell request has been submitted successfully.','success'),
(4,'Verification Completed','Your crop has been verified successfully.','info'),
(5,'Payment Released','Your payment has been transferred to your bank account.','success'),
(2,'New Service Request','A new complaint has been assigned to you.','warning');
-- ============================================================
-- SAMPLE ANNOUNCEMENTS
-- ============================================================
INSERT INTO announcements(title, content, target_role, created_by)VALUES
('MSP Rates Updated','Government has announced revised MSP prices for Kharif crops.','all',1),
('PM-KISAN Installment','Eligible farmers will receive ₹2000 directly to their bank accounts.','farmer',1),
('E-KYC Mandatory','E-KYC verification is mandatory for receiving government benefits.','farmer',1),
('Employee Meeting','All agriculture officers should attend the monthly review meeting.','employee',1);
-- ============================================================
-- SAMPLE NOTIFICATIONS FOR ALL FARMERS
-- ============================================================
INSERT INTO notifications
(user_id, title, message, type)
SELECT id, 'Welcome to AgriConnect','Thank you for registering with AgriConnect.','info'
FROM users
WHERE role = 'farmer';

-- ============================================================
-- POSTGRESQL STORED PROCEDURES & FUNCTIONS
-- ============================================================

CREATE OR REPLACE FUNCTION sp_register_user(
    p_name VARCHAR,
    p_phone VARCHAR,
    p_password_hash VARCHAR,
    p_role user_role,
    p_village VARCHAR,
    p_district VARCHAR,
    p_aadhar VARCHAR,
    p_bank VARCHAR,
    p_ifsc VARCHAR
) RETURNS INTEGER AS $$
DECLARE
    new_id INTEGER;
BEGIN
    INSERT INTO users (name, phone, password_hash, role, village, district, aadhar_number, bank_account, ifsc_code, is_active)
    VALUES (p_name, p_phone, p_password_hash, COALESCE(p_role, 'farmer'::user_role), p_village, p_district, p_aadhar, p_bank, p_ifsc, TRUE)
    RETURNING id INTO new_id;
    RETURN new_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sp_create_sell_request(
    p_farmer_id INTEGER,
    p_crop_id INTEGER,
    p_quantity NUMERIC,
    p_image_url VARCHAR,
    p_village VARCHAR,
    p_harvest_date DATE,
    p_notes TEXT,
    p_geo_lat NUMERIC,
    p_geo_lng NUMERIC,
    p_expected_amount NUMERIC
) RETURNS INTEGER AS $$
DECLARE
    new_id INTEGER;
BEGIN
    INSERT INTO sell_requests (
        farmer_id, crop_id, quantity, image_url, village, harvest_date, notes, geo_lat, geo_lng, expected_amount
    ) VALUES (
        p_farmer_id, p_crop_id, p_quantity, p_image_url, p_village, p_harvest_date, p_notes, p_geo_lat, p_geo_lng, p_expected_amount
    ) RETURNING id INTO new_id;

    INSERT INTO notifications (user_id, title, message, type)
    SELECT id, 'New Sell Request', 'A new sell request requires verification.', 'info'
    FROM users WHERE role = 'employee';

    RETURN new_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sp_verify_sell_request(
    p_request_id INTEGER,
    p_user_id INTEGER,
    p_action VARCHAR,
    p_rejection_reason TEXT,
    p_remarks TEXT
) RETURNS VARCHAR AS $$
DECLARE
    v_status sell_status;
    v_farmer_id INTEGER;
    v_msg TEXT;
    v_notif_title VARCHAR;
    v_notif_type notification_type;
BEGIN
    v_status := CASE WHEN p_action = 'verify' THEN 'verified'::sell_status ELSE 'rejected'::sell_status END;

    UPDATE sell_requests
    SET status = v_status,
        verified_by = p_user_id,
        verified_at = CURRENT_TIMESTAMP,
        rejection_reason = p_rejection_reason
    WHERE id = p_request_id
    RETURNING farmer_id INTO v_farmer_id;

    IF p_remarks IS NOT NULL AND length(trim(p_remarks)) > 0 THEN
        INSERT INTO remarks (entity_type, entity_id, message, created_by)
        VALUES ('sell_request', p_request_id, p_remarks, p_user_id);
    END IF;

    IF p_action = 'verify' THEN
        v_msg := 'Your sell request has been verified and forwarded for approval.';
        v_notif_title := 'Sell Request Verified';
        v_notif_type := 'success';
    ELSE
        v_msg := 'Your sell request was rejected. Reason: ' || COALESCE(p_rejection_reason, 'N/A');
        v_notif_title := 'Sell Request Rejected';
        v_notif_type := 'error';
    END IF;

    IF v_farmer_id IS NOT NULL THEN
        INSERT INTO notifications (user_id, title, message, type)
        VALUES (v_farmer_id, v_notif_title, v_msg, v_notif_type);
    END IF;

    RETURN v_status::VARCHAR;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sp_approve_sell_request(
    p_request_id INTEGER,
    p_user_id INTEGER,
    p_action VARCHAR,
    p_procurement_date DATE,
    p_rejection_reason TEXT,
    p_remarks TEXT
) RETURNS VARCHAR AS $$
DECLARE
    v_status sell_status;
    v_farmer_id INTEGER;
BEGIN
    v_status := CASE WHEN p_action = 'approve' THEN 'approved'::sell_status ELSE 'rejected'::sell_status END;

    UPDATE sell_requests
    SET status = v_status,
        approved_by = p_user_id,
        approved_at = CURRENT_TIMESTAMP,
        procurement_date = p_procurement_date,
        rejection_reason = p_rejection_reason
    WHERE id = p_request_id
    RETURNING farmer_id INTO v_farmer_id;

    IF p_action = 'approve' AND p_procurement_date IS NOT NULL THEN
        INSERT INTO procurement (request_id, schedule_date)
        VALUES (p_request_id, p_procurement_date)
        ON CONFLICT (request_id) DO UPDATE SET schedule_date = EXCLUDED.schedule_date;
    END IF;

    RETURN v_status::VARCHAR;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sp_mark_payment_done(
    p_request_id INTEGER,
    p_payment_amount NUMERIC,
    p_transaction_ref VARCHAR
) RETURNS BOOLEAN AS $$
DECLARE
    v_farmer_id INTEGER;
BEGIN
    UPDATE sell_requests
    SET status = 'payment_done'::sell_status,
        payment_status = 'done'::payment_status,
        payment_amount = p_payment_amount,
        transaction_ref = p_transaction_ref,
        payment_date = CURRENT_TIMESTAMP
    WHERE id = p_request_id
    RETURNING farmer_id INTO v_farmer_id;

    UPDATE procurement
    SET payment_status = 'done'::payment_status,
        payment_amount = p_payment_amount,
        transaction_ref = p_transaction_ref,
        payment_date = CURRENT_TIMESTAMP
    WHERE request_id = p_request_id;

    IF v_farmer_id IS NOT NULL THEN
        INSERT INTO notifications (user_id, title, message, type)
        VALUES (
            v_farmer_id,
            'Payment Processed',
            'Payment of ₹' || p_payment_amount || ' has been credited. Ref: ' || COALESCE(p_transaction_ref, 'N/A'),
            'success'
        );
    END IF;

    RETURN TRUE;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sp_create_service_request(
    p_farmer_id INTEGER,
    p_type service_type,
    p_subject VARCHAR,
    p_description TEXT,
    p_media_url VARCHAR,
    p_priority priority_level
) RETURNS INTEGER AS $$
DECLARE
    new_id INTEGER;
BEGIN
    INSERT INTO service_requests (farmer_id, type, subject, description, media_url, priority)
    VALUES (p_farmer_id, p_type, p_subject, p_description, p_media_url, COALESCE(p_priority, 'medium'::priority_level))
    RETURNING id INTO new_id;

    INSERT INTO notifications (user_id, title, message, type)
    SELECT id, 'New Service Request', 'A new service request requires attention.', 'info'
    FROM users WHERE role IN ('employee', 'admin');

    RETURN new_id;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION sp_update_service_request(
    p_request_id INTEGER,
    p_user_id INTEGER,
    p_action VARCHAR,
    p_resolution_notes TEXT,
    p_escalation_reason TEXT,
    p_remarks TEXT
) RETURNS VARCHAR AS $$
DECLARE
    v_status service_status;
    v_farmer_id INTEGER;
    v_title VARCHAR;
    v_msg TEXT;
    v_type notification_type;
BEGIN
    IF p_action = 'accept' THEN
        v_status := 'in_progress'::service_status;
        UPDATE service_requests SET status = v_status, handled_by = p_user_id, assigned_at = CURRENT_TIMESTAMP WHERE id = p_request_id RETURNING farmer_id INTO v_farmer_id;
        v_title := 'Request Accepted'; v_msg := 'Your service request is now being processed.'; v_type := 'info';
    ELSIF p_action = 'resolve' THEN
        v_status := 'resolved'::service_status;
        UPDATE service_requests SET status = v_status, resolved_at = CURRENT_TIMESTAMP, resolution_notes = p_resolution_notes WHERE id = p_request_id RETURNING farmer_id INTO v_farmer_id;
        v_title := 'Request Resolved'; v_msg := 'Your service request has been resolved. ' || COALESCE(p_resolution_notes, ''); v_type := 'success';
    ELSIF p_action = 'reject' THEN
        v_status := 'rejected'::service_status;
        UPDATE service_requests SET status = v_status, resolved_at = CURRENT_TIMESTAMP, resolution_notes = p_resolution_notes WHERE id = p_request_id RETURNING farmer_id INTO v_farmer_id;
        v_title := 'Request Rejected'; v_msg := 'Your service request was rejected. ' || COALESCE(p_resolution_notes, ''); v_type := 'error';
    ELSIF p_action = 'escalate' THEN
        v_status := 'escalated'::service_status;
        UPDATE service_requests SET status = v_status, escalated_at = CURRENT_TIMESTAMP, escalation_reason = p_escalation_reason WHERE id = p_request_id RETURNING farmer_id INTO v_farmer_id;
        v_title := 'Request Escalated'; v_msg := 'Your service request has been escalated to admin for further action.'; v_type := 'warning';
    END IF;

    IF p_remarks IS NOT NULL AND length(trim(p_remarks)) > 0 THEN
        INSERT INTO remarks (entity_type, entity_id, message, created_by)
        VALUES ('service_request', p_request_id, p_remarks, p_user_id);
    END IF;

    IF v_farmer_id IS NOT NULL AND v_title IS NOT NULL THEN
        INSERT INTO notifications (user_id, title, message, type)
        VALUES (v_farmer_id, v_title, v_msg, v_type);
    END IF;

    RETURN v_status::VARCHAR;
END;
$$ LANGUAGE plpgsql;