--============================================================
-- AGRICONNECT DATABASE SCHEMA (POSTGRESQL)
--============================================================
-- ============================================================
-- DROP TABLES (Optional)
-- ============================================================
DROP TABLE IF EXISTS crops CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TYPE IF EXISTS user_role CASCADE;
DROP TYPE IF EXISTS crop_category CASCADE;
DROP TYPE IF EXISTS crop_season CASCADE;
-- ============================================================
-- ENUM TYPES
-- ============================================================
CREATE TYPE user_role AS ENUM ('farmer','employee','admin');
CREATE TYPE crop_category AS ENUM ('cereal','pulse','oilseed','vegetable','fruit', 'other');
CREATE TYPE crop_season AS ENUM ('kharif','rabi','zaid','all');
-- ============================================================
-- FUNCTION FOR updated_at
-- ============================================================
CREATE OR REPLACE FUNCTION update_timestamp()
RETURNS TRIGGER AS
$$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$
LANGUAGE plpgsql;
-- ============================================================
-- USERS TABLE
-- ============================================================
CREATE TABLE users
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    phone VARCHAR(15) UNIQUE NOT NULL,
    email VARCHAR(100),
    password_hash VARCHAR(255) NOT NULL,
    role user_role NOT NULL DEFAULT 'farmer',
    aadhar_number VARCHAR(12),
    village VARCHAR(100),
    district VARCHAR(100),
    state VARCHAR(100) DEFAULT 'Andhra Pradesh',
    pincode VARCHAR(6),
    bank_account VARCHAR(20),
    ifsc_code VARCHAR(11),
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);
-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_users_role
ON users(role);
CREATE INDEX idx_users_phone
ON users(phone);
CREATE INDEX idx_users_district
ON users(district);
-- ============================================================
-- UPDATE TRIGGER
-- ============================================================
CREATE TRIGGER trg_users_timestamp
BEFORE UPDATE
ON users
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
-- ============================================================
-- CROPS TABLE
-- ============================================================
CREATE TABLE crops
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    name_telugu VARCHAR(100),
    category crop_category DEFAULT 'cereal',
    govt_price NUMERIC(10,2) NOT NULL,
    unit VARCHAR(20) DEFAULT 'quintal',
    season crop_season DEFAULT 'all',
    is_active BOOLEAN DEFAULT TRUE,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by INTEGER,
    CONSTRAINT fk_crop_user
        FOREIGN KEY(updated_by)
        REFERENCES users(id)
        ON DELETE SET NULL
);
COMMENT ON COLUMN crops.govt_price
IS 'Government MSP Price Per Quintal';
-- ============================================================
-- CROPS INDEXES
-- ============================================================
CREATE INDEX idx_crop_name
ON crops(name);
CREATE INDEX idx_crop_category
ON crops(category);
CREATE INDEX idx_crop_season
ON crops(season);
CREATE INDEX idx_crop_active
ON crops(is_active);
-- ============================================================
-- SAMPLE USERS
-- Password = Admin@123
-- ============================================================
INSERT INTO users
(name, phone, email, password_hash, role, district, village)
VALUES
(
'System Administrator',
'9000000001',
'admin@agriconnect.gov.in',
'$2b$10$rQZ8kHWnvhSGjOJ1BKYvIeXEXJPQIhVN4VqEYJBdKMHpGkWZe5pAm',
'admin',
'Nellore',
'Secretariat'
),
(
'Ramaiah Sachivalayam',
'9000000002',
'employee1@agriconnect.gov.in',
'$2b$10$rQZ8kHWnvhSGjOJ1BKYvIeXEXJPQIhVN4VqEYJBdKMHpGkWZe5pAm',
'employee',
'Nellore',
'Kovur'
),
(
'Suresh Kumar',
'9000000003',
'farmer1@agriconnect.gov.in',
'$2b$10$rQZ8kHWnvhSGjOJ1BKYvIeXEXJPQIhVN4VqEYJBdKMHpGkWZe5pAm',
'farmer',
'Nellore',
'Allur'
),
(
'Lakshmi Devi',
'9000000004',
'farmer2@agriconnect.gov.in',
'$2b$10$rQZ8kHWnvhSGjOJ1BKYvIeXEXJPQIhVN4VqEYJBdKMHpGkWZe5pAm',
'farmer',
'Nellore',
'Kavali'
),
(
'Venkata Rao',
'9000000005',
'farmer3@agriconnect.gov.in',
'$2b$10$rQZ8kHWnvhSGjOJ1BKYvIeXEXJPQIhVN4VqEYJBdKMHpGkWZe5pAm',
'farmer',
'Nellore',
'Gudur'
);
-- ============================================================
-- SAMPLE CROPS
-- ============================================================
INSERT INTO crops
(name, name_telugu, category, govt_price, season, updated_by)
VALUES
('Paddy (Common)','వరి (సాధారణ)','cereal',2183.00,'kharif',1),

('Paddy (Grade A)','వరి (గ్రేడ్ A)','cereal',2203.00,'kharif',1),

('Wheat','గోధుమ','cereal',2275.00,'rabi',1),

('Maize','మొక్కజొన్న','cereal',2090.00,'kharif',1),

('Groundnut','వేరుశనగ','oilseed',6783.00,'kharif',1),

('Sunflower','పొద్దుతిరుగుడు','oilseed',6760.00,'kharif',1),

('Red Gram (Tur)','కంది పప్పు','pulse',7000.00,'kharif',1),

('Black Gram','మినప పప్పు','pulse',8558.00,'kharif',1),

('Green Gram','పెసర పప్పు','pulse',8682.00,'kharif',1),

('Cotton (Medium)','పత్తి (మీడియం)','other',7121.00,'kharif',1),

('Cotton (Long)','పత్తి (లాంగ్)','other',7521.00,'kharif',1),

('Soybean','సోయాబీన్','oilseed',4600.00,'kharif',1);
-- ============================================================
-- ENUM TYPES
-- ============================================================
CREATE TYPE sell_status AS ENUM
('pending','verified','rejected','approved','scheduled','completed','payment_done');
CREATE TYPE payment_status AS ENUM
('pending','processing','done');
CREATE TYPE service_type AS ENUM
('subsidy','complaint','crop_damage','loan','scheme','other');
CREATE TYPE service_status AS ENUM
('pending','in_progress','escalated','resolved','rejected');
CREATE TYPE priority_level AS ENUM
('low','medium','high','urgent');
-- ============================================================
-- SELL REQUESTS TABLE
-- ============================================================
CREATE TABLE sell_requests
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id INTEGER NOT NULL,
    crop_id INTEGER NOT NULL,
    quantity NUMERIC(10,2) NOT NULL,
    govt_price NUMERIC(10,2),
    expected_amount NUMERIC(12,2),
    image_url VARCHAR(500),
    geo_lat NUMERIC(10,8),
    geo_lng NUMERIC(11,8),
    village VARCHAR(100),
    harvest_date DATE,
    notes TEXT,
    status sell_status DEFAULT 'pending',
    verified_by INTEGER,
    verified_at TIMESTAMP,
    rejection_reason TEXT,
    approved_by INTEGER,
    approved_at TIMESTAMP,
    procurement_date DATE,
    payment_status payment_status DEFAULT 'pending',
    payment_amount NUMERIC(12,2),
    transaction_ref VARCHAR(100),
    payment_date TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_sell_farmer
        FOREIGN KEY(farmer_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_sell_crop
        FOREIGN KEY(crop_id)
        REFERENCES crops(id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_verified_by
        FOREIGN KEY(verified_by)
        REFERENCES users(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_approved_by
        FOREIGN KEY(approved_by)
        REFERENCES users(id)
        ON DELETE SET NULL
);
-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_sell_farmer
ON sell_requests(farmer_id);
CREATE INDEX idx_sell_status
ON sell_requests(status);
CREATE INDEX idx_sell_crop
ON sell_requests(crop_id);
CREATE INDEX idx_sell_created
ON sell_requests(created_at);
-- ============================================================
-- UPDATE TRIGGER
-- ============================================================
CREATE TRIGGER trg_sell_requests_timestamp
BEFORE UPDATE
ON sell_requests
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
-- ============================================================
-- SERVICE REQUESTS
-- ============================================================
CREATE TABLE service_requests
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id INTEGER NOT NULL,
    type service_type NOT NULL,
    subject VARCHAR(200) NOT NULL,
    description TEXT NOT NULL,
    media_url VARCHAR(500),
    status service_status DEFAULT 'pending',
    priority priority_level DEFAULT 'medium',
    handled_by INTEGER,
    assigned_at TIMESTAMP,
    escalated_to INTEGER,
    escalated_at TIMESTAMP,
    escalation_reason TEXT,
    resolved_at TIMESTAMP,
    resolution_notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_service_farmer
        FOREIGN KEY(farmer_id)
        REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_handled_by
        FOREIGN KEY(handled_by)
        REFERENCES users(id)
        ON DELETE SET NULL,
    CONSTRAINT fk_escalated_to
        FOREIGN KEY(escalated_to)
        REFERENCES users(id)
        ON DELETE SET NULL
);
-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_service_farmer
ON service_requests(farmer_id);
CREATE INDEX idx_service_status
ON service_requests(status);
CREATE INDEX idx_service_type
ON service_requests(type);
CREATE INDEX idx_service_priority
ON service_requests(priority);
-- ============================================================
-- UPDATE TRIGGER
-- ============================================================
CREATE TRIGGER trg_service_requests_timestamp
BEFORE UPDATE
ON service_requests
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
-- ============================================================
-- PROCUREMENT TABLE
-- ============================================================
CREATE TABLE procurement
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INTEGER UNIQUE NOT NULL,
    schedule_date DATE NOT NULL,
    schedule_time TIME,
    location VARCHAR(200),
    officer_name VARCHAR(100),
    vehicle_number VARCHAR(20),
    actual_quantity NUMERIC(10,2),
    payment_status payment_status DEFAULT 'pending',
    payment_amount NUMERIC(12,2),
    transaction_ref VARCHAR(100),
    bank_ref VARCHAR(100),
    payment_date TIMESTAMP,
    notes TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_procurement_request
        FOREIGN KEY(request_id)
        REFERENCES sell_requests(id)
        ON DELETE CASCADE
);
-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX idx_procurement_date
ON procurement(schedule_date);
CREATE INDEX idx_procurement_payment
ON procurement(payment_status);
-- ============================================================
-- UPDATE TRIGGER
-- ============================================================
CREATE TRIGGER trg_procurement_timestamp
BEFORE UPDATE
ON procurement
FOR EACH ROW
EXECUTE FUNCTION update_timestamp();
-- ============================================================
-- SAMPLE SELL REQUESTS
-- ============================================================
INSERT INTO sell_requests
(farmer_id,crop_id,quantity,village,status,notes)
VALUES
(3,1,25.50,'Allur','pending','Good quality paddy harvested last week'),
(4,5,15.00,'Kavali','verified','Fresh groundnut harvest'),
(5,7,10.00,'Gudur','approved','Organic red gram'),
(3,10,20.00,'Allur','completed','Medium variety cotton');
-- ============================================================
-- SAMPLE SERVICE REQUESTS
-- ============================================================
INSERT INTO service_requests
(farmer_id,type,subject,description,status,priority)
VALUES
(3,'subsidy','PM-KISAN Payment Delay','I have not received the PM-KISAN payment for the last quarter.','pending','high'),
(4,'complaint','Crop Damage Due to Pests','Groundnut crop damaged by pests.','in_progress','urgent'),
(5,'crop_damage','Flood Damage','Flood damaged my Red Gram crop.','escalated','high'),
(3,'loan','Agricultural Loan','I want to apply for a crop loan.','resolved','medium');
-- ============================================================
-- ENUM TYPES
-- ============================================================
CREATE TYPE entity_type AS ENUM
('sell_request','service_request');
CREATE TYPE notification_type AS ENUM
('info','success','warning','error');
CREATE TYPE target_role AS ENUM
( 'all','farmer','employee','admin');
-- ============================================================
-- REMARKS TABLE
-- ============================================================
CREATE TABLE remarks
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type entity_type NOT NULL,
    entity_id INTEGER NOT NULL,
    message TEXT NOT NULL,
    created_by INTEGER NOT NULL,
    is_internal BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_remarks_user
        FOREIGN KEY(created_by)
        REFERENCES users(id)
        ON DELETE CASCADE
);
-- ============================================================
-- REMARKS INDEXES
-- ============================================================
CREATE INDEX idx_remarks_entity
ON remarks(entity_type, entity_id);
CREATE INDEX idx_remarks_created_by
ON remarks(created_by);
-- ============================================================
-- NOTIFICATIONS TABLE
-- ============================================================
CREATE TABLE notifications
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    type notification_type DEFAULT 'info',
    is_read BOOLEAN DEFAULT FALSE,
    link VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user
        FOREIGN KEY(user_id)
        REFERENCES users(id)
        ON DELETE CASCADE
);
-- ============================================================
-- NOTIFICATION INDEXES
-- ============================================================
CREATE INDEX idx_notifications_user
ON notifications(user_id);
CREATE INDEX idx_notifications_read
ON notifications(is_read);
-- ============================================================
-- ANNOUNCEMENTS TABLE
-- ============================================================
CREATE TABLE announcements
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(200) NOT NULL,
    content TEXT NOT NULL,
    target_role target_role DEFAULT 'all',
    is_active BOOLEAN DEFAULT TRUE,
    created_by INTEGER NOT NULL,
    expires_at DATE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_announcements_user
        FOREIGN KEY(created_by)
        REFERENCES users(id)
        ON DELETE CASCADE
);
-- ============================================================
-- ANNOUNCEMENTS INDEXES
-- ============================================================
CREATE INDEX idx_announcements_role
ON announcements(target_role);
CREATE INDEX idx_announcements_active
ON announcements(is_active);
-- ============================================================
-- SAMPLE REMARKS
-- ============================================================
INSERT INTO remarks
(entity_type, entity_id, message, created_by, is_internal)
VALUES
('sell_request',1,'Sell request received successfully.',2,FALSE),
('sell_request',2,'Crop quality verified by procurement officer.',2,TRUE),
('service_request',1,'Farmer contacted through phone.',2,FALSE),
('service_request',3,'District agriculture officer informed.',1,TRUE);
-- ============================================================
-- SAMPLE NOTIFICATIONS
-- ============================================================
INSERT INTO notifications(user_id, title, message, type)VALUES
(3,'Sell Request Submitted','Your crop sell request has been submitted successfully.','success'),
(4,'Verification Completed','Your crop has been verified successfully.','info'),
(5,'Payment Released','Your payment has been transferred to your bank account.','success'),
(2,'New Service Request','A new complaint has been assigned to you.','warning');
-- ============================================================
-- SAMPLE ANNOUNCEMENTS
-- ============================================================
INSERT INTO announcements(title, content, target_role, created_by)VALUES
('MSP Rates Updated','Government has announced revised MSP prices for Kharif crops.','all',1),
('PM-KISAN Installment','Eligible farmers will receive ₹2000 directly to their bank accounts.','farmer',1),
('E-KYC Mandatory','E-KYC verification is mandatory for receiving government benefits.','farmer',1),
('Employee Meeting','All agriculture officers should attend the monthly review meeting.','employee',1);
-- ============================================================
-- SAMPLE NOTIFICATIONS FOR ALL FARMERS
-- ============================================================
INSERT INTO notifications
(user_id, title, message, type)
SELECT id, 'Welcome to AgriConnect','Thank you for registering with AgriConnect.','info'
FROM users
WHERE role = 'farmer';